In [27]:
import torch

In [28]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 35, -59,  55, -34,  80,  70])

In [29]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [30]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
input = torch.empty(2, 3)
input

tensor([[2.3694e-38, 2.3694e-38, 2.3694e-38],
        [2.3694e-38, 2.3694e-38, 2.3694e-38]])

In [33]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [34]:
linspace = torch.linspace(2, 10, steps=5)
linspace

tensor([ 2.,  4.,  6.,  8., 10.])

In [35]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [36]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [37]:
a = torch.empty((2,3), dtype=torch.int64)
emptylike = torch.empty_like(a)
emptylike

tensor([[      4451867827792, 4044267787726618624, 4044267787726618624],
        [4044267787726618624, 4044267787726618624, 4044267787726618624]])

## CPU vs GPU

In [38]:
import time
import torch
import numpy as np


device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [39]:
%%time
start_time = time.time()


zeros=torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time

print(f"{elapsed_time: .8f}")

 0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


In [40]:
# pip install numpy
print(np.__version__)

2.0.1


In [41]:
print(torch.cuda.is_available())
print(torch.__version__)


True
2.4.0+cu124


In [42]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)


tensor([1, 1, 1, 1, 1, 1, 1, 1, 0, 1])


In [43]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [44]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [45]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [46]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
print(out)

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


In [47]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [48]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0,2) #swap Oth pos with 2nd pos
out.shape

torch.Size([4, 3, 2])

In [49]:
tensor1= torch.tensor([1, 2, 3])
tensor2= torch.tensor([4, 5, 6])
tensor3= torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
import torch.nn as nn 

sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-3.0725, -6.8991,  5.2267], grad_fn=<SqueezeBackward4>)


In [51]:
import torch.nn.functional as F

tensor1 = torch.tensor([-0.4, 2.9, 3.0])

softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0172, 0.4668, 0.5159])

In [52]:
int_64 = torch.randint(1, (3,2)).float()
float_32 = torch.rand(2,3)

print(int_64.dtype)
print(float_32.dtype)

result = int_64 @ float_32
print("result: ", result)

torch.float32
torch.float32
result:  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [53]:
a = torch.rand(2, 3, 5)
x, y, z = a.shape
a = a.view(x, y, z)
print(x, y, z)
print(a.shape)

2 3 5
torch.Size([2, 3, 5])
